import { GoogleGenAI } from "@google/genai";

export const removeBackgroundWithGemini = async (base64Image: string): Promise<string> => {
  if (!process.env.API_KEY) {
    throw new Error("API Key is missing. Please check your configuration.");
  }

  const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });
  
  // Extract base64 data if it has the prefix
  const base64Data = base64Image.replace(/^data:image\/(png|jpeg|jpg);base64,/, '');

  try {
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: {
        parts: [
          {
            inlineData: {
              data: base64Data,
              mimeType: 'image/png'
            }
          },
          {
            text: "Change the background of this photo to a solid, pure white color suitable for an ID photo. Keep the person completely unchanged, sharp, and high quality. Do not crop the person."
          }
        ]
      }
    });

    // Extract the image from the response
    if (response.candidates?.[0]?.content?.parts) {
      for (const part of response.candidates[0].content.parts) {
        if (part.inlineData && part.inlineData.data) {
           return `data:image/png;base64,${part.inlineData.data}`;
        }
      }
    }
    
    throw new Error("No image generated by Gemini.");

  } catch (error) {
    console.error("Error calling Gemini API:", error);
    throw error;
  }
};
